### PR TITLE
Licenses and supporting documentation

### PR DESCRIPTION
**Pull request by cgbosse**
Issue 82

Type: Documentation

Licenses, contributor agreements, file header txt, etc. for review by Cameron.

### CODE REVIEW

**Review by da2ce7 — CHANGES_REQUESTED** [review]
@cgbosse 
Sorry for the long time to review.

## 1. Markdown Formatting.

The markdown formating in:
[license/cc-by-sa.md](license/cc-by-sa.md)
 is good.

Please conform:
[license/agpl-3.0.md](license/agpl-3.0.md)

## 2. Contributor Agreement

After reviewing your contributor agreement, I came to the conclusion that the template that you isn't that great; It grants Nautilus too much rights, and is too broad.

I have decided to model our contributor agreement upon:
[The Fedora Project Contributor Agreement](https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement)

Here is my draft with modifications:
https://github.com/da2ce7/chinese-ideographs/blob/issue-82-contributor_agreement/documentation/Contributor_Agreement.md

Please Review.

You can also cherry-pick this commit if you wish: 
https://github.com/da2ce7/chinese-ideographs/commit/b08eb891ffd347eade7a0a1a50e18c73cd9a6435

**Comment by cgbosse** [comment]
Hi @da2ce7,

## AGPL-3.0

> Please conform: [license/agpl-3.0.md](license/agpl-3.0.md)

What do you mean exactly by this? I just took the license from your link and included it as from the original.

## Contributor Agreement:

> I have decided to model our contributor agreement upon: [The Fedora Project Contributor Agreement](https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement)
> 
> Here is my draft with modifications: https://github.com/da2ce7/chinese-ideographs/blob/issue-82-contributor_agreement/documentation/Contributor_Agreement.md
>

Fine with me, I read through the linked text, though we will then have to:
- Create the list of the mentioned acceptable licenses, do you already have it in mind? Don`t we run the risk to have to mention too many licenses this way?
- Implement a click through acceptance , how would this be done?

>Section 7 – Acceptance.
>
>You must signify Your assent to the terms of this NCCA through specific electronic means established by Nautilus (such as by click-through acceptance means).
>


On the other hand, could one make it somehow simpler just stating in the Readme to not have to keep a record such signed agreements, that by submitting any work the default licenses will be applied. Could there be an automatic reply upon the creation of any pull request that makes this point evident again? This in combination with the GPG signature would then be the proof of validity which is made automatically part of the process.

Thank you.

**Comment by da2ce7** [comment]
Hello @cgbosse 

1.

I looked into the markdown of both documents: [license/cc-by-sa.md](license/cc-by-sa.md) and [license/agpl-3.0.md](license/agpl-3.0.md).

I found that the structure of the markdown in the CC-BY-SA document was much better than the structure in the AGPL 3.0 document, hence it would be nice if the AGPL markdown was improved to the quality of the CC-BY-SA.

However, this is low priority, so don't worry about it. It can happen at any time without effect.

2.

> Create the list of the mentioned acceptable licenses, do you already have it in mind? Don`t we run the risk to have to mention too many licenses this way?

We only really need to list four licenses: CC-BY-SA, CC-0, AGPL, MIT-0

So I don't think that it is so much work.

Additionally, the link doesn't need to be pointing to our website. It can easily be a page within this pull request.

> Implement a click through acceptance , how would this be done?

I suggest that we simply remove the "(such as by click-through acceptance means)", and let the "electronic means" be undefined for the moment.

:)

Cam.

**Comment by cgbosse** [comment]
Hi Cameron,
I implemented the changes as requested.
I opted to include the list of Nautilus acceptable license as a different section within the same document.
I updated the links.
Changed the folder naming from license to licensing.
Updated the Contributing document with the appropriate reference to the Contributor agreement.
Updated the Readme document with a link to the CONTRIBUTING document.
It should all be good now.

**Review by da2ce7 — APPROVED** [review]
@cgbosse 

Good Work. Lets go ahead and merge it. :)

**Comment by cgbosse** [comment]
Good morning @da2ce7,

Thank you. It was teamwork.
I proceed to merge.

**Pull request merged**
